
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('jobs').del()
    .then(function () {
      // Inserts seed entries
      return knex('jobs').insert([
        {position: "Jr Python Developer", description:"Career Evolutions is searching for a Jr. Python Developer for a fast growing hi-tech company based in Tempe, AZ . This is a full-time, direct-hire opportunity with compensation up to $70K plus benefits.",  link:"https://www.indeed.com/jobs?q=Junior%20Developer&l=Phoenix%2C%20AZ&vjk=75896f65ed627ab6", contact:"", location:"Arizona"},
        {position: "UI/UX Web Developer", description:"Helix House, Arizona’s #1 Ranked Digital Advertising Agency is hiring a highly driven WEB DEVELOPER/CODER. This is a full-time IN HOUSE position.", link: "https://www.indeed.com/jobs?q=web%20developer&l=Arizona&vjk=482bc7e07e8a5657", contact:"", location:"Arizona"},
        {position: "Frontend Web Developer", description:"We are looking for a full time frontend web developer to join our team as soon as possible.Are you a rock star web developer with some personality and a zest for pixel perfect, and just generally awesome, code?", link: "https://www.indeed.com/jobs?q=web%20developer&l=Arizona&vjk=2270b6191ca36917", contact:"", location:"Arizona"},
        {position: "Data Visualization Specialist (UI/UX)", description:"Honeywell International is a $40 billion diversified Fortune 100 leader with more than 130,000 employees in 100 countries around the world.", link:"https://www.indeed.com/viewjob?jk=58157ada17347388&from=tp-serp&tk=1c52ft398b097dln", contact:"", location:"Arizona"},
        {position: "Full Stack Web Instructor", description:"We are looking for a Full Stack Web Instructor who will be responsible for effective delivery of all course materials and curriculum for academic programs offered by Woz U, to prepare the students for the workplace.", link: "https://www.indeed.com/viewjob?jk=067658d19d4a03a3&from=tp-serp&tk=1c52ft398b097dln", contact:"", location:"Arizona"},
        {position: "Intern- IT- Web Applications Developer", description:"The US Foods Summer Internship Program provides a forum for students to apply classroom skills and academic training in a real world business environment. ", link: "https://www.indeed.com/viewjob?jk=97715816900c19de&from=tp-serp&tk=1c52ft398b097dln", contact:"", location:"Arizona"},
        {position: "Digital & Web Designer", description:"Divvy Digital is looking for a contract designer to help take its clients Web and TV Menu Design to the next level. If you are an expert in Web Design and have a knack for motion graphics this role would be perfect for you", link: "https://www.indeed.com/viewjob?jk=812a89aef0e02192&from=tp-serp&tk=1c52g4dcmb097an4", contact:"", location: "Washington"},
        {position: "Web Applications Tester", description:"Are you passionate and enthusiastic about a career in the Automotive, Manufacturing, Supply Chain, Chemical or Electronics/Semi-Conductor industries? One of the clients IT web hosting company located in North of Seattle WA is looking to hire Web Application Tester personnel.", link:"https://www.indeed.com/viewjob?jk=1532d38fb67ec77b&from=tp-serp&tk=1c52gfi8qb097b9l", contact:"", location:"Washington"},
        {position: "Interaction Designer ", description:"The job of an Interaction Designer is to envision how people experience our products and bring that vision to life in a way that feels inspired, refined and even magical.", link: "https://www.indeed.com/viewjob?jk=b153640ae7e5ef4e&from=tp-serp&tk=1c52gfi8qb097b9l", contact:"", location:"Washington"},
        {position: "UI/UX Designer", description:"As a designer at This Place, you’ll be a crucial part of delivering innovative digital products, platforms, and experiences from conception through design. You’ll use your design chops, passion, and perspective.", link:"https://www.indeed.com/viewjob?jk=340ec2a75521e978&from=tp-serp&tk=1c52gfi8qb097b9l", contact:"", location:"Washington"},
        {position: "Shopify Website Designer, Print Designer, Photo Editor", description:"A key part to cultivating and nourishing these relationships are building a bridge between our online presence and in person experience. We are seeking a Shopify web designer with photography and photo editing skills to help support our food focused team.", link: "https://www.indeed.com/viewjob?jk=9f68bab914fab334&from=tp-serp&tk=1c52h466db097dl8", contact:"", location:"California"},
        {position: "Web Developer/Web Designer Intern", description:"In this role the web developer will create pages for the corporate website working closely with the product manager to assist in building a strong image for the company", link: "https://www.indeed.com/viewjob?jk=5eaeb13dd2d67345&from=tp-serp&tk=1c52h466db097dl8", contact:"", location:"California"},
        {position: "Digital Design UX Researcher", description:"Deliver creative concepts, editorial concepts, visual design solutions or research in support of Bank of America products and services offerings. Works with technology partners to ensure defect-free implementation of design solutions.", link: "https://www.indeed.com/viewjob?jk=cf4924f0b0ef3d07&from=tp-serp&tk=1c52h466db097dl8", contact:"", location:"California"},
        {position: "Software Intern", description:"Capella Space is looking for an enthusiastic Software intern to work with the spacecraft engineering team. The intern will gain hands-on experience with building small satellites in a fast paced environment.", link: "https://www.indeed.com/viewjob?jk=f9cde4342142be90&from=tp-serp&tk=1c52h466db097dl8", contact:"", location:"California"},
        {position: "User Experience (UX) Designer, Indeed Hire", description:"We are looking for a designer who can help improve the UX of Indeed Hire, a full service recruiting agency, powered with Indeed technology.", link: "https://www.indeed.com/viewjob?jk=b118cdc89995c41b&from=tp-serp&tk=1c52hvdqpb097cjb", contact:"", location:"Texas"},
        {position: "Design - Intern", description:"Purpose of Job Executes production and/or coding of marketing tactics and/or graphic user interface needs, under direct supervision. Works closely with key partners/suppliers to ensure quality output and production. ", link: "https://www.indeed.com/viewjob?jk=f1d6f0bfcb4887e6&from=tp-serp&tk=1c52hvdqpb097cjb", contact:"", location:"Texas"},
        {position: "Database Developer", description:"Looking to join a fast growing real estate tech company? Want the freedom to develop new and innovative applications, with the satisfaction of first hand development to implementation success?", link: "https://www.indeed.com/viewjob?jk=baadf3241a04aac1&from=tp-serp&tk=1c52i83tnb0978uk", contact:"", location:"Texas"},
        {position: "Software Engineer Intern - Texas A&M", description:"We're looking for software engineering interns to help our teams expand their existing platforms and develop new features and products. This 10-12 week internship program will be based in our Dallas office. ", link: "https://www.indeed.com/viewjob?jk=c1331dcf791c9c15&from=tp-serp&tk=1c52i83tnb0978uk", contact:"", location:"Texas"},
        {position: "Software Engineer", description:"As a member of our software engineering group you will jump into a team tasked with creating and supporting innovative solutions that advance the business and support our clients using some of the latest & greatest technologies and software engineering practices and disciplines.", link: "https://www.indeed.com/viewjob?jk=8808c1a671d26ebb&from=tp-serp&tk=1c52iurekb0978sk", contact:"", location:"New York"},
        {position: "UI Designer", description:"We are a tech startup recognized as a leader in product innovation and design. Looking for a UI design ninja to help us improve our current platform design, work with clients on prototypes and workshops, and work on new product launches.", link: "https://www.indeed.com/viewjob?jk=7fabdefd13f2260d&from=tp-serp&tk=1c52iurekb0978sk", contact:"", location:"New York"},
        {position: "UX Designer", description:"Blue State Digital, a creative strategy and tech agency, seeks a UX designer in our New York office. Applicants should have experience designing innovative, elegant user experiences that meet user needs and drive measurable results for organizations.", link: "https://www.indeed.com/viewjob?jk=6e2adc254a753e2f&from=tp-serp&tk=1c52iurekb0978sk", contact:"", location:"New York"},
        {position: "Software Engineer (Java/J2EE)", description:"As a member of our Software Engineering Group you will dive head-first into creating innovative solutions that advance businesses and careers.", link: "https://www.indeed.com/viewjob?jk=ddf316790ef1e0d4&from=tp-serp&tk=1c52iurekb0978sk", contact:"", location:"New York"},
        {position: "Web Developer/Web Designer Internship", description:"J. Lewis & Co is an up and coming event planning company that is looking for a web presence design developer to partner with to assist with social media. The web developer intern is responsible for designing, coding and modifying the J. Lewis & Co website, from layout to function and according to certain specifications", link: "https://www.indeed.com/viewjob?jk=b7d7e0b6b778680e&from=tp-serp&tk=1c52jglsab097f67", contact:"", location:"Colorado"},
        {position: "Entry Level Software Developer - Campus Recruiting", description:"CGI is seeking students interested in summer internship opportunities in the Information Technology field. CGI is more than just an IT consulting company; we are a global organization offering a world of opportunities.", link: "https://www.indeed.com/viewjob?jk=7cf649fac178581e&from=tp-serp&tk=1c52jglsab097f67", contact:"", location:"Colorado"},
        {position: "Designer Temporary position", description:"The Designer incorporates the brand vision, seasonal design themes and product line direction to design commercially compelling sock and knit accessories that achieve both brand and quantitative goals", link: "https://www.indeed.com/viewjob?jk=4f8eba940e9ef3a8&from=tp-serp&tk=1c52jp19db097ct4", contact:"", location:"Colorado"}
      ]);
    });
};
